version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
jobs:
  build-and-push-ecr:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with AWS ECR
          command: |
            echo $AWS_ACCESS_KEY_ID | docker login -u AWS --password-stdin https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - run:
          name: Build Docker Image
          command: docker build -t $ECR_REPOSITORY:$CIRCLE_SHA1 .
      - run:
          name: Tag Docker Image
          command: docker tag $ECR_REPOSITORY:$CIRCLE_SHA1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$CIRCLE_SHA1
      - run:
          name: Push Docker Image to ECR
          command: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$CIRCLE_SHA1
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-push-ecr
